//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace easyCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class candidato
    {
        public int codigo { get; set; }
        public string nome { get; set; }
        public string email { get; set; }
        public string skype { get; set; }
        public string telefone { get; set; }
        public string linkedin { get; set; }
        public string estado { get; set; }
        public string cidade { get; set; }
        public string portfolio { get; set; }
        public Nullable<int> disponibilidade { get; set; }
        public Nullable<int> horario { get; set; }
        public Nullable<double> salario { get; set; }
        public string informacao_bancaria { get; set; }
        public string conta_nome { get; set; }
        public string cpf { get; set; }
        public string banco_nome { get; set; }
        public string agencia { get; set; }
        public string conta { get; set; }
        public Nullable<int> tipo_conta_corrente { get; set; }
        public Nullable<int> tipo_conta_poupanca { get; set; }
        public Nullable<int> ionic { get; set; }
        public Nullable<int> android { get; set; }
        public Nullable<int> ios { get; set; }
        public Nullable<int> html { get; set; }
        public Nullable<int> css { get; set; }
        public Nullable<int> bootstrap { get; set; }
        public Nullable<int> jquery { get; set; }
        public Nullable<int> angularjs { get; set; }
        public Nullable<int> java { get; set; }
        public Nullable<int> aspnet_mvc { get; set; }
        public Nullable<int> c { get; set; }
        public Nullable<int> c_plusplus { get; set; }
        public Nullable<int> cake { get; set; }
        public Nullable<int> django { get; set; }
        public Nullable<int> majento { get; set; }
        public Nullable<int> php { get; set; }
        public Nullable<int> vue { get; set; }
        public Nullable<int> wordpress { get; set; }
        public Nullable<int> phyton { get; set; }
        public Nullable<int> ruby { get; set; }
        public Nullable<int> sql_server { get; set; }
        public Nullable<int> my_sql { get; set; }
        public Nullable<int> salesforce { get; set; }
        public Nullable<int> photoshop { get; set; }
        public Nullable<int> illustrator { get; set; }
        public Nullable<int> seo { get; set; }
        public string crud { get; set; }
    }
}
